"""
DC Feasibility Tool v4 — FastAPI Backend Entry Point
======================================================
Creates the FastAPI application and registers all API route modules.

Run with:
    cd backend/
    uvicorn main:app --reload --port 8000

The --reload flag means the server restarts automatically when you
save a file. The frontend (React) will run on port 5173 and talk
to this backend on port 8000.

API Documentation (auto-generated by FastAPI):
    Interactive (Swagger):  http://localhost:8000/docs
    OpenAPI JSON:           http://localhost:8000/openapi.json

Route modules registered:
    /api/sites      — Site CRUD, KML upload, geocoding  (Page 1)
    /api/climate    — Weather fetch, climate analysis    (Page 2)
    /api/scenarios  — Run scenarios, scoring, sensitivity (Pages 3–4)
    /api/green      — Green energy dispatch              (Page 5)
    /api/export     — Report generation and downloads    (Page 6)
    /api/settings   — Runtime diagnostics + cache ops    (Page 7)

Reference: Architecture Agreement v2.0, Section 2 (Stack), Section 8 (Phase 4)
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

# ── Import all route modules ──
# Each module creates its own APIRouter with a prefix.
# We import the router object and include it in the app below.
from api.routes_site import router as site_router
from api.routes_scenario import router as scenario_router
from api.routes_climate import router as climate_router
from api.routes_green import router as green_router
from api.routes_export import router as export_router
from api.routes_settings import router as settings_router
from api.routes_grid import router as grid_router


# ─────────────────────────────────────────────────────────────
# Create the FastAPI application
# ─────────────────────────────────────────────────────────────
# The metadata here shows up in the auto-generated API docs.
# When you visit http://localhost:8000/docs, you'll see these
# details at the top of the page.

app = FastAPI(
    title="DC Feasibility Tool v4",
    description=(
        "Data center site feasibility analysis engine. "
        "Evaluates candidate sites for power capacity, cooling efficiency, "
        "infrastructure fit, and green energy potential."
    ),
    version="4.1.3",
)


# ─────────────────────────────────────────────────────────────
# CORS Middleware
# ─────────────────────────────────────────────────────────────
# CORS = Cross-Origin Resource Sharing.
#
# When your React app (running on http://localhost:5173) makes an
# HTTP request to this backend (running on http://localhost:8000),
# the browser blocks it by default because they're on different
# "origins" (different ports = different origins).
#
# This middleware tells the browser: "It's OK, I trust requests
# from localhost:5173." Without this, every API call from the
# frontend would fail with a CORS error in the browser console.
#
# In production, you'd replace the localhost origins with your
# actual domain (e.g., "https://dc-feasibility.metlen.com").

app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",   # Vite dev server (default)
        "http://localhost:3000",   # Alternative React dev port
        "http://127.0.0.1:5173",  # Sometimes needed on Windows
        "http://127.0.0.1:3000",
    ],
    allow_credentials=True,
    allow_methods=["*"],   # Allow all HTTP methods (GET, POST, PUT, DELETE)
    allow_headers=["*"],   # Allow all headers (Content-Type, Authorization, etc.)
)


# ─────────────────────────────────────────────────────────────
# Register Route Modules
# ─────────────────────────────────────────────────────────────
# app.include_router() adds all endpoints from a router to the app.
# Each router already has its own prefix (e.g., /api/sites), so
# the full URL for listing sites would be:
#     GET http://localhost:8000/api/sites
#
# The order here doesn't matter for functionality, but it affects
# the order endpoints appear in the API docs.

app.include_router(site_router)       # /api/sites + /api/geocode + /api/reference-data
app.include_router(climate_router)    # /api/climate/*
app.include_router(scenario_router)   # /api/scenarios/*
app.include_router(green_router)      # /api/green/*
app.include_router(export_router)     # /api/export/*
app.include_router(settings_router)   # /api/settings/*
app.include_router(grid_router)       # /api/grid/*


# ─────────────────────────────────────────────────────────────
# Root and Health Endpoints
# ─────────────────────────────────────────────────────────────

@app.get("/")
async def root():
    """Root endpoint — confirms the server is running.

    Also shows the available route prefixes so a developer hitting
    the base URL knows where to go.
    """
    return {
        "status": "running",
        "tool": "DC Feasibility Tool v4",
        "version": "4.1.3",
        "docs": "Visit /docs for interactive API documentation",
        "api_routes": {
            "sites": "/api/sites",
            "climate": "/api/climate",
            "scenarios": "/api/scenarios",
            "green_energy": "/api/green",
            "grid_context": "/api/grid",
            "export": "/api/export",
            "reference_data": "/api/reference-data",
            "geocoding": "/api/geocode",
        },
    }


async def health_check():
    """Health check endpoint — used by the frontend to verify backend connectivity.

    The frontend calls this when the app loads. If it fails, the UI
    shows a "Backend not connected" warning.

    Also returns the engine version and data storage status.
    """
    from api.store import count_sites, count_solar_profiles, count_weather_caches

    return {
        "status": "healthy",
        "version": "4.1.3",
        "phase": "6/7 — Interactive UI + Export",
        "sites_stored": count_sites(),
        "weather_cached": count_weather_caches(),
        "solar_profiles_cached": count_solar_profiles(),
    }


app.get("/health")(health_check)
app.get("/api/health")(health_check)
